### ISSUE TITLE
앱 이름 관련 이슈

### ISSUE THREAD

**Issue by Kim-jeongmin** [Kim-jeongmin/Kimmessicorp#11]
생각해보니 애플리케이션의 이름에 대해서 논의 안한 것 같은데 그냥 kimmessi로 할까요? 아니면 다른 괜찮은 이름을 지을까요? 그거에 따라서 앱아이콘을 생각해보는 것도 좋은 방법 같습니다.

_Originally posted by @SeongBinYoon in https://github.com/Kim-jeongmin/Kimmessicorp/issues/7#issuecomment-646954459_

**Comment by Kim-jeongmin** [comment]
저는 킴메시도 나쁘지 않다고 생각합니다만, 더 좋은 의견 있으신가요?

**Comment by yewonkang00** [comment]
킴메시는 팀명이고 게시판에 맞는 이름을 짓는 것이 좋지 않나요..??

**Comment by yewonkang00** [comment]
저도 한번 생각해보겠습니다.

**Comment by SeongBinYoon** [comment]
저도 따로 짓는게 낫다는 생각이 듭니다. 좋은 이름 한 번 생각해 보겠습니다.

**Comment by yewonkang00** [comment]
수다스러운의 의미를 가지고 있는 "Chatty", "Talky"
또는 큰소리로 말하다라는 의미의 "Shout Out" 어때요??

**Comment by SeongBinYoon** [comment]
shout out 좋은 것 같습니다. 샤라웃

**Comment by Kim-jeongmin** [comment]
샤라웃 킴메시~
샤라웃 좋네요 ㅋㅋ
