### ISSUE TITLE
menu 구성

### ISSUE THREAD

**Issue by yewonkang00** [Kim-jeongmin/Kimmessicorp#12]
menu 부분에 무엇을 넣으면 좋을까요?

**Comment by Kim-jeongmin** [comment]
일단 ID밖에 안뒀는데 제 생각엔.. 게시판 종류들? 같은 거 있으면 좋겠네요.
게시판도 약간 종류 나누고..

**Comment by SeongBinYoon** [comment]
저도 같은 생각입니다. 무엇에 관한 글인지 카테고리 별로 나누는 것도 좋을 것 같습니다.

**Comment by yewonkang00** [comment]
개인정보를 적어놓은 activity를 만드는 것도 좋을 것 같아요!
그래서 menu 에 개인정보 버튼 누르면 보여줄 수 있게??

**Comment by yewonkang00** [comment]
아니면 메뉴에 아이디, 이름, 나이 이런것 올리는 것도 좋을것같아요.

**Comment by SeongBinYoon** [comment]
개인정보를 적어놓은 activity를 만드는거 좋은 생각 같네요. 사용자 정보를 알려주게끔이요.

**Comment by yewonkang00** [comment]
나중에 시간되면 게시물 검색하는 기능을 추가하는 것도 좋을 것 같네요!

**Comment by Kim-jeongmin** [comment]
개인 정보하는 건 제가 메뉴했으니까 제가 하도록하겠습니다. 검색기능을 추가하는 것도 좋네요

**Comment by SeongBinYoon** [comment]
네 알겠습니다. db에서 가져와 게시판에 올리는건 제가 한번 해보도록 하겠습니다.

**Comment by yewonkang00** [comment]
아 혹시 작성한 게시물 말씀하시는 건가요?? 그부분은 제가 하고있어서요..ㅜㅜ

**Comment by SeongBinYoon** [comment]
아 그럼 제가 list view 클릭시 보여지는 화면 해보겠습니다.
