### ISSUE TITLE
회원 정보 창 대충 만들었는데 어떤 식으로 할까요

### ISSUE THREAD

**Issue by Kim-jeongmin** [Kim-jeongmin/Kimmessicorp#13]
<img src="https://user-images.githubusercontent.com/55871387/85203406-978f7580-b348-11ea-9f98-00fb1f112b39.jpg"  width="300" height="600">

**Comment by yewonkang00** [comment]
잘하셨네요!!
글씨 조금만 더 키워주시고 각각 앞에 ID: , 이름: ...이런식으로 넣으면 좋을거 같아요!

**Comment by Kim-jeongmin** [comment]
알겠습니다. 나중에 아이디 비밀번호 수정기능도 추가할 예정인데 그 기능 넣는거 괜찮겠죠?

**Comment by yewonkang00** [comment]
오오 넣을 수 있으면 좋죠!

**Comment by Kim-jeongmin** [comment]
![앱화원정보화면2](https://user-images.githubusercontent.com/55871387/85221703-fc060f80-b3f0-11ea-8ae5-d110f2aeaf84.jpg)

말씀하신대로 만들었습니다 이정도로만 할까요?

**Comment by yewonkang00** [comment]
네!! 너무 좋네요!!

**Comment by Kim-jeongmin** [comment]
감사합니다. 이렇게 마무리하도록 하겠습니다.
