### ISSUE TITLE
인트로 화면

### ISSUE THREAD

**Issue by yewonkang00** [Kim-jeongmin/Kimmessicorp#15]
<img src="https://user-images.githubusercontent.com/54140431/85224222-a7b85b00-b403-11ea-9a07-64bcff6a1ecf.png" width="300" height="600">

인트로화면 디자인 해봤는데 어떤가요?

**Comment by Kim-jeongmin** [comment]
오 되게 잘만드셨네 ㄷㄷ

**Comment by SeongBinYoon** [comment]
좋은것 같아요!

**Comment by yewonkang00** [comment]
넵 이걸로 할게요~
