### ISSUE TITLE
아이콘 문제

### ISSUE THREAD

**Issue by yewonkang00** [Kim-jeongmin/Kimmessicorp#23]
아이콘을 파란색아이콘으로 다바꿔놨는데 그 앱 기록버튼??그걸 누르면 이렇게  다른 아이콘이 뜨더라구요ㅜㅜ저만 그런가요?? 이거 어떻게 고쳐야할까요??
<img src="https://user-images.githubusercontent.com/54140431/85350711-d2f29580-b53c-11ea-88aa-9152b70ac27c.png" width="300" height="600">

**Comment by Kim-jeongmin** [comment]
실행 결과 아이콘 잘나옵니다.

핸드폰 문제인 것 같습니다..

**Comment by SeongBinYoon** [comment]
저도 아이콘은 파란거 잘 나오네요. 다만 listview를 누르고 게시글로 들어가면 앱이 튕겨버리네요.

**Comment by Kim-jeongmin** [comment]
그부분 지금 제가 보고있습니다

**Comment by SeongBinYoon** [comment]
네 알겠습니다.

**Comment by yewonkang00** [comment]
아 원래는 안튕겼었나요?? 제가 머 잘못건드렸나요??ㅜㅜ

**Comment by SeongBinYoon** [comment]
네 원래는 실행이 됐어요. 근데 딱히 view쪽을 건드리신건 아니던데요..

**Comment by Kim-jeongmin** [comment]
그 부분 제가 수정했습니다.
