### ISSUE TITLE
viewactivity 댓글창 이슈

### ISSUE THREAD

**Issue by SeongBinYoon** [Kim-jeongmin/Kimmessicorp#26]
현재 댓글창을 viewActivity에 넣어 viewActivity 화면에서 댓글을 쓸수있게끔 했는데 그렇게 되면 댓글을 보기 위해서는 따로 commentActivity로 넘어가야 됩니다. 이렇게 그냥 해볼까요?
아니면 viewActivity에서 댓글창을 없애고 아예 commentActivity에서 댓글을 쓰고 읽게끔 해볼까요?

**Comment by Kim-jeongmin** [comment]
음.. 약간 유튜브처럼 해보면 좋을 것 같아요..

![Screenshot_20200623-200936_YouTube](https://user-images.githubusercontent.com/55871387/85396904-913e0b00-b58d-11ea-843c-095c759824c2.jpg)

이렇게 하나정도만 올리고 들어가서 댓글 보는식으로?
자세한건 유튜브 보면 더 좋을 것 같아요

**Comment by SeongBinYoon** [comment]
댓글을 하나 올리기 위해선 listview를 써야하는데 부분적으로만 listview가 보여지게끔 하는 방법 혹시 아시나요?

**Comment by SeongBinYoon** [comment]
그 부분은 찾아봐도 잘 안나오더라구요.

**Comment by Kim-jeongmin** [comment]
Textview로 intent 하면 될듯한데 .. 아닌가요

**Comment by SeongBinYoon** [comment]
아 한번 해보겠습니다.
