### ISSUE TITLE
앱 설치 시

### ISSUE THREAD

**Issue by yewonkang00** [Kim-jeongmin/Kimmessicorp#32]
앱 설치하면 앱이 2개 생기든데 저만 그런가요??

**Comment by SeongBinYoon** [comment]
엇 그러네요 실행에 문제가 있진 않지만 두개가 생겼네요
<img width="309" alt="스크린샷 2020-06-25 오후 4 36 26" src="https://user-images.githubusercontent.com/55236612/85676933-04688e00-b702-11ea-8d5e-347823f36945.png">

**Comment by yewonkang00** [comment]
두개 다 작동 잘되나요?

**Comment by yewonkang00** [comment]
오 해결된건가요??

**Comment by SeongBinYoon** [comment]
네 작동은 잘됩니다. 이부분 제가 pr올렸습니다. 근데 문제가 있는게, andriodmanifests 파일에 intent filter에 MAIN과 LAUNCHER 가 두개여서 하나를 지우면 인트로가 작동이 안되든 메뉴창에 회원정보가 안 뜨든 둘 중 하나네요..

**Comment by yewonkang00** [comment]
아 ㅜㅜ 그럼 일단 원래대로 해야겠네요...

**Comment by SeongBinYoon** [comment]
넵 해결했습니다!

**Comment by yewonkang00** [comment]
네?? 앱 2개 안생기나요??

**Comment by SeongBinYoon** [comment]
네. 앱 2개 안생기는 것 같습니다.
