### ISSUE TITLE
menu pr 관련 이슈

### ISSUE THREAD

**Issue by Kim-jeongmin** [Kim-jeongmin/Kimmessicorp#6]
제가 menu pr을 해야하는데 못해서 제 코드를 따로 커밋에서 확인해주시면 감사하겠습니다. 죄송합니다

**Comment by SeongBinYoon** [comment]
확인했습니다. 전체적으로 UI 개선된 부분이 보기 좋은 것 같습니다. 로그인과 회원가입 창도 깔끔하고 메뉴창도 정돈되어 좋은 것 같습니다. 카테고리별 게시판이나 검색어 기능 등 메뉴창에 추가할 수 있는 부분에 대해서도 생각해보겠습니다. 감사합니다.

**Comment by yewonkang00** [comment]
아이디를 메뉴 프로필 창으로 넘기는 것이 어려울 수 있겠다고 생각했는데 잘하셨네요. 저도 비슷한 방법으로 글작성할때 아이디를 넘겨받을 수 있도록 해야겠습니다. 사용자 이름은 받은 아이디를 DB로 넘겨 아이디가 일치하는 사람의 이름을 찾아내어 넘겨받으면 되지 않을까요? 수고하셨습니다.

**Comment by Kim-jeongmin** [comment]
> 아이디를 메뉴 프로필 창으로 넘기는 것이 어려울 수 있겠다고 생각했는데 잘하셨네요. 저도 비슷한 방법으로 글작성할때 아이디를 넘겨받을 수 있도록 해야겠습니다. 사용자 이름은 받은 아이디를 DB로 넘겨 아이디가 일치하는 사람의 이름을 찾아내어 넘겨받으면 되지 않을까요? 수고하셨습니다.

아마 그렇게 해야할 것 같습니다.
