### ISSUE TITLE
앱아이콘

### ISSUE THREAD

**Issue by yewonkang00** [Kim-jeongmin/Kimmessicorp#7]
![doodle-1388091_1920](https://user-images.githubusercontent.com/54140431/85095426-55711180-b22c-11ea-9cb8-6f4fa151a737.jpg)
앱아이콘으로 이거 어때요??
일단 그냥 찾아본건데 더 좋은거 있으면 올려주세요.

**Comment by yewonkang00** [comment]
![doodle-1388097_1920](https://user-images.githubusercontent.com/54140431/85095494-7f2a3880-b22c-11ea-9e09-3871107fd57e.jpg)
이거도 봐주세요.

**Comment by SeongBinYoon** [comment]
게시판 애플리케이션을 생각해보면 앞의 앱아이콘이 더 잘 어울리는 것 같기도 해요. 마치 블랙보드 앱 아이콘 같아서 좋네요^^

**Comment by SeongBinYoon** [comment]
여러 생각이 모여서 나무처럼 풍성해지는 게시판이라는 취지로 아래 아이콘도 괜찮네요!

**Comment by yewonkang00** [comment]
> 여러 생각이 모여서 나무처럼 풍성해지는 게시판이라는 취지로 아래 아이콘도 괜찮네요!

저도 그 생각하고 가져와봤는데 괜찮은 것 같네요!

**Comment by Kim-jeongmin** [comment]
저 아이콘이 앱 아이콘이 되면 앱 설치하고 휴대폰에서는 어떻게 보이나요

**Comment by yewonkang00** [comment]
![Screenshot_2020-06-20-14-09-55-650_com miui gallery](https://user-images.githubusercontent.com/54140431/85192976-d5b47700-b2ff-11ea-8921-003552d2044b.jpg)
이런식이런식으로 되네요...잘안보이긴하네요

**Comment by yewonkang00** [comment]
아니면 나무 부분만 할까요??
더 괜찮은 그림 있으면 올려주세요

**Comment by Kim-jeongmin** [comment]
저렇게 보이는 것이 더 나을 것 같아요. 더 좋은 그림 있으면 올려보겠습니다

**Comment by Kim-jeongmin** [comment]
![image](https://user-images.githubusercontent.com/55871387/85195150-31d0c880-b30b-11ea-9e37-d9037d8837ad.png)

**Comment by Kim-jeongmin** [comment]
간단하게 이것도 좋을 듯 합니다

**Comment by yewonkang00** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ
근데 너무 게시판 느낌 안나지 않나요??

**Comment by Kim-jeongmin** [comment]
그런가요.. ㅋㅋ 저는 그냥 다른 커뮤니티 사이트들 로고들도 다 이런 식으로 각자의 로고를 쓰고 있길래 한 번 올려봤습니다 ㅎㅎ

**Comment by SeongBinYoon** [comment]
생각해보니 애플리케이션의 이름에 대해서 논의 안한 것 같은데 그냥 kimmessi로 할까요? 아니면 다른 괜찮은 이름을 지을까요? 그거에 따라서 앱아이콘을 생각해보는 것도 좋은 방법 같습니다.

**Comment by Kim-jeongmin** [comment]
네 좋은 생각이네요 그건 따로 이슈를 만들었습니다

**Comment by SeongBinYoon** [comment]
네 차차 생각해보면 될 것 같네요

**Comment by yewonkang00** [comment]
앱이름 Shout Out에 맞게 이런 이미지 어때요??
![megaphone-2223049_1280](https://user-images.githubusercontent.com/54140431/85197377-8ed47a80-b31b-11ea-8495-27354d6161f9.png)
![megaphone-1468168_1920](https://user-images.githubusercontent.com/54140431/85197380-9136d480-b31b-11ea-8f5d-de19a35b536b.png)

**Comment by Kim-jeongmin** [comment]
첫번째 아이콘 심플하고 좋네요 앱 이름과도 잘 맞고요

**Comment by SeongBinYoon** [comment]
한 눈에 들어오는 인상적인 아이콘인 것 같아요. 전 개인적으로 아래 아이콘이 좋은것 같습니다!

**Comment by Kim-jeongmin** [comment]
계속 보니까 두번째 꺼도 괜찮아보이네요

**Comment by yewonkang00** [comment]
<img src="https://user-images.githubusercontent.com/54140431/85223061-e3025c00-b3fa-11ea-8541-b5c11837c4a5.jpg" width="300" height="600">

<img src="https://user-images.githubusercontent.com/54140431/85223138-6f148380-b3fb-11ea-8a06-ff79516b1291.jpg" width="300" height="600">

어떤것이 더 좋은가요??

**Comment by Kim-jeongmin** [comment]
뭔가 휴대폰에서 보이는건 첫번째가 좋네요

**Comment by yewonkang00** [comment]
저도 첫번째꺼가 눈에 더 잘띄고 좋은 것 같습니다.

**Comment by yewonkang00** [comment]
그럼 첫번째걸로 할까요?

**Comment by Kim-jeongmin** [comment]
저는 좋습니다.

**Comment by SeongBinYoon** [comment]
인트로 시안이 좋아서 첫번째걸로 해도 될듯하네요.

**Comment by yewonkang00** [comment]
넵!
