### ISSUE TITLE
앱 배경색

### ISSUE THREAD

**Issue by yewonkang00** [Kim-jeongmin/Kimmessicorp#8]
6803A9F4
배경색으로 이런 하늘색 어때요?

**Comment by yewonkang00** [comment]
![image](https://user-images.githubusercontent.com/54140431/85098441-ba7d3500-b235-11ea-8415-8cd48e8fa907.png)
보노보노같은색 ㅋㅋㅋㅋㅋ

**Comment by yewonkang00** [comment]
좀 더 연하게 해야겠다

**Comment by SeongBinYoon** [comment]
조금 더 연한 하늘색도 괜찮은 것 같아요!

**Comment by Kim-jeongmin** [comment]
보노보노 좋네

**Comment by yewonkang00** [comment]
<img src="https://user-images.githubusercontent.com/54140431/85223198-e34f2700-b3fb-11ea-9f1e-bf3afac437c9.png" width="100" height="100">

이 색은 어떤가요?

**Comment by Kim-jeongmin** [comment]
뭐가 다른건지 저는 구분 못하겠습니다 ㅎㅎ.. 근데 저는 인트로에 나오는 색깔이랑 똑같으면 더 좋을듯..? 싶습니다.^^

**Comment by yewonkang00** [comment]
![image](https://user-images.githubusercontent.com/54140431/85225635-b3a91a80-b40d-11ea-9e97-fc9551fb4151.png)

이렇게 나오는데 괜찮나요??

**Comment by Kim-jeongmin** [comment]
음...
좀 그렇긴 하네요 쪼끔 연한 색으로 하는 게 나을 듯 합니다

**Comment by SeongBinYoon** [comment]
연하게 하거나 아예 흰색도 나쁘지 않을듯 합니다.
